replicaCount: 1
image:
    repository: null
    tag: null
    pullPolicy: IfNotPresent
service:
    name: customer-service
    type: ClusterIP
    internalPort: 8080
    externalPort: 8080
container:
    name: customer-service
resources:
    limits:
        cpu: 100m
        memory: 128Mi
    requests:
        cpu: 100m
        memory: 128Mi
