replicaCount: 1
image:
    repository: null
    tag: null
    pullPolicy: Always
service:
    name: catalog-service
    externalPort: 80
    internalPort: 8080
container:
    name: catalog-service
resources:
    limits:
        cpu: 100m
        memory: 128Mi
    requests:
        cpu: 100m
        memory: 128Mi