replicaCount: 1
image:
    repository: robjahn/keptn-orders-front-end
    tag: 1
    pullPolicy: Always
service:
    name: front-end
    externalPort: 80
    internalPort: 8080
container:
    name: front-end
resources:
    limits:
        cpu: 100m
        memory: 128Mi
    requests:
        cpu: 100m
        memory: 128Mi
